# Generated by Django 4.2.7 on 2026-07-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('APPOINTMENT_REMINDER', 'Appointment Reminder'), ('ELIGIBILITY_REMINDER', 'Eligibility Reminder'), ('EMERGENCY_REQUEST', 'Emergency Blood Request'), ('CAMPAIGN', 'Campaign Announcement'), ('REQUEST_UPDATE', 'Request Status Update'), ('DONATION_COMPLETE', 'Donation Complete'), ('REWARD_EARNED', 'Reward Earned'), ('SYSTEM', 'System Notification'), ('HOSPITAL_SUBSCRIPTION', 'Hospital Subscription Payment')], max_length=30),
        ),
    ]
