# Generated by Django 4.2.7 on 2026-07-20 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_donorhealthrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='O+', max_length=3)),
                ('rh_factor', models.CharField(choices=[('POSITIVE', 'Rh+'), ('NEGATIVE', 'Rh-')], default='POSITIVE', max_length=10)),
                ('hiv_status', models.CharField(choices=[('NEGATIVE', 'Negative (Passed)'), ('POSITIVE', 'Positive (Failed)'), ('PENDING', 'Pending Test')], default='NEGATIVE', max_length=15)),
                ('hep_b_status', models.CharField(choices=[('NEGATIVE', 'Negative (Passed)'), ('POSITIVE', 'Positive (Failed)'), ('PENDING', 'Pending Test')], default='NEGATIVE', max_length=15)),
                ('hep_c_status', models.CharField(choices=[('NEGATIVE', 'Negative (Passed)'), ('POSITIVE', 'Positive (Failed)'), ('PENDING', 'Pending Test')], default='NEGATIVE', max_length=15)),
                ('syphilis_status', models.CharField(choices=[('NEGATIVE', 'Negative (Passed)'), ('POSITIVE', 'Positive (Failed)'), ('PENDING', 'Pending Test')], default='NEGATIVE', max_length=15)),
                ('malaria_status', models.CharField(choices=[('NEGATIVE', 'Negative (Passed)'), ('POSITIVE', 'Positive (Failed)'), ('PENDING', 'Pending Test')], default='NEGATIVE', max_length=15)),
                ('hemoglobin_g_dl', models.FloatField(default=14.0, help_text='Hemoglobin in g/dL')),
                ('unit_status', models.CharField(choices=[('PENDING', 'Pending Screening'), ('APPROVED', 'Approved / Safe'), ('REJECTED', 'Rejected'), ('QUARANTINED', 'Quarantined')], default='PENDING', max_length=20)),
                ('abnormal_findings', models.TextField(blank=True)),
                ('has_abnormal_findings', models.BooleanField(default=False)),
                ('tested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_records', to='donors.donor')),
                ('inventory_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_records', to='inventory.bloodinventory')),
                ('tested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_lab_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tested_at'],
            },
        ),
    ]
