# Generated by Django 4.2.7 on 2026-07-20 11:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorHealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('hemoglobin', models.FloatField(blank=True, help_text='Hemoglobin level in g/dL', null=True)),
                ('systolic_bp', models.IntegerField(blank=True, help_text='Systolic BP in mmHg', null=True)),
                ('diastolic_bp', models.IntegerField(blank=True, help_text='Diastolic BP in mmHg', null=True)),
                ('pulse_rate', models.IntegerField(blank=True, help_text='Pulse rate in bpm', null=True)),
                ('weight_kg', models.FloatField(blank=True, help_text='Weight in kg', null=True)),
                ('temperature_c', models.FloatField(blank=True, help_text='Temperature in Celsius', null=True)),
                ('screening_result', models.CharField(choices=[('PASSED', 'Passed / Normal'), ('ATTENTION', 'Attention Needed'), ('FAILED', 'Deferred')], default='PASSED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='donors.donor')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
