# Generated by Django 4.2.7 on 2026-07-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='has_blood_bank',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='has_emergency_services',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='opening_hours',
            field=models.CharField(default='24/7 Emergency & Blood Bank', max_length=150),
        ),
        migrations.AddField(
            model_name='hospital',
            name='services',
            field=models.TextField(blank=True, default='Blood Bank, Emergency Care, Transfusion, ICU, Lab Testing'),
        ),
    ]
