# Generated by Django 4.2.7 on 2026-07-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_hospital_has_blood_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='subscription_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('DEACTIVATED', 'Deactivated')], default='EXPIRED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['subscription_status'], name='hospitals_h_subscri_455689_idx'),
        ),
    ]
