# Generated by Django 4.2.7 on 2026-06-22 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ELIGIBLE', 'Eligible'), ('TEMP_INELIGIBLE', 'Temporarily Ineligible'), ('PERM_INELIGIBLE', 'Permanently Ineligible')], max_length=20)),
                ('age_ok', models.BooleanField()),
                ('weight_ok', models.BooleanField()),
                ('medical_history_ok', models.BooleanField()),
                ('recent_surgeries_ok', models.BooleanField()),
                ('pregnancy_status_ok', models.BooleanField()),
                ('infectious_diseases_ok', models.BooleanField()),
                ('medication_use_ok', models.BooleanField()),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eligibility_checks', to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_checks', to='donors.donor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['donor', 'created_at'], name='eligibility_donor_i_874572_idx')],
            },
        ),
    ]
