# Generated by Django 4.2.7 on 2026-07-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('donor', 'Donor'), ('patient', 'Patient'), ('hospital_staff', 'Hospital Staff'), ('blood_bank_admin', 'Blood Bank Administrator'), ('system_admin', 'System Administrator')], default='donor', max_length=20),
        ),
    ]
