# Generated by Django 4.2.7 on 2026-07-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='fulfillment_type',
            field=models.CharField(blank=True, choices=[('DIRECT_DONATION', 'Direct Donation'), ('INVENTORY', 'From Inventory')], max_length=30, null=True),
        ),
    ]
