# Generated by Django 4.2.7 on 2026-07-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_bloodrequest_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
