# Generated by Django 4.2.7 on 2026-07-16 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
        ('requests', '0002_bloodrequest_fulfillment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_requests', to='donors.donor'),
        ),
    ]
