# Generated by Django 4.2.7 on 2026-10-03 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_hospital_subscription_end_date_and_more'),
        ('requests', '0004_alter_bloodrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_requests', to='hospitals.hospital'),
        ),
    ]
