# Generated by Django 4.2.7 on 2026-07-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='priority',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent'), ('Emergency', 'Emergency')], default='Normal', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='recipient_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='scheduled_delivery',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_age_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_age_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_blood_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_eligibility',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
