# Generated by Django 4.2.7 on 2026-06-22 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BRONZE', 'Bronze Donor'), ('SILVER', 'Silver Donor'), ('GOLD', 'Gold Donor'), ('PLATINUM', 'Platinum Donor'), ('LIFE_SAVER', 'Life Saver'), ('EMERGENCY_HERO', 'Emergency Hero'), ('TOP_COMMUNITY', 'Top Community Donor')], max_length=50, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=255)),
                ('criteria', models.JSONField(default=dict)),
                ('points_required', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['points_required'],
            },
        ),
        migrations.CreateModel(
            name='DonorReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_rewards', to='rewards.badge')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='donors.donor')),
            ],
            options={
                'ordering': ['-awarded_at'],
                'unique_together': {('donor', 'badge')},
            },
        ),
    ]
