# Generated by Django 4.2.7 on 2026-07-23 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_alter_bloodrequest_status'),
        ('hospitals', '0003_hospital_subscription_end_date_and_more'),
        ('payments', '0003_hospitalsubscriptionpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('HOSPITAL_SUBSCRIPTION', 'Hospital Subscription'), ('BLOOD_REQUEST_PAYMENT', 'Blood Request Payment')], default='BLOOD_REQUEST_PAYMENT', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='blood_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='requests.bloodrequest'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('downloadable_format', models.TextField(blank=True, default='')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='payments.payment')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
                ('active_status', models.BooleanField(default=False)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='hospitals.hospital')),
            ],
        ),
    ]
