# Generated by Django 4.2.7 on 2026-07-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_hospital_payment_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pdf_invoice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
