# Generated by Django 4.2.7 on 2026-09-01 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_invoice_pdf_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=100, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payer_name', models.CharField(blank=True, max_length=255)),
                ('payment_method', models.CharField(max_length=30)),
                ('transaction_reference', models.CharField(blank=True, max_length=255)),
                ('pdf_receipt', models.CharField(blank=True, max_length=255, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='payments.payment')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
