# Generated by Django 4.2.7 on 2026-06-22 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0001_initial'),
        ('hospitals', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=3)),
                ('quantity', models.IntegerField(default=0)),
                ('collection_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('used', 'Used'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donors.donor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='hospitals.hospital')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hospital', 'blood_group', 'status'], name='inventory_b_hospita_936679_idx'), models.Index(fields=['expiration_date'], name='inventory_b_expirat_072998_idx')],
                'unique_together': {('hospital', 'blood_group', 'collection_date')},
            },
        ),
    ]
