# Generated by Django 4.2.7 on 2026-07-22 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospitals', '0003_hospital_subscription_end_date_and_more'),
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalSubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('months', models.IntegerField(default=1)),
                ('payment_method', models.CharField(choices=[('MTN_MOMO', 'MTN Mobile Money'), ('ORANGE_MONEY', 'Orange Money'), ('CASH', 'Cash'), ('CARD', 'Card')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('external_reference', models.CharField(blank=True, max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_period_start', models.DateTimeField(blank=True, null=True)),
                ('subscription_period_end', models.DateTimeField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='hospitals.hospital')),
                ('staff_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_subscription_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hospital', 'status'], name='payments_ho_hospita_e07b94_idx'), models.Index(fields=['invoice_number'], name='payments_ho_invoice_73d859_idx'), models.Index(fields=['transaction_id'], name='payments_ho_transac_c27e90_idx')],
            },
        ),
    ]
