# Generated by Django 4.2.7 on 2026-06-22 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_donations', models.PositiveIntegerField(default=0)),
                ('total_blood_units', models.PositiveIntegerField(default=0)),
                ('lives_saved', models.PositiveIntegerField(default=0)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('next_eligible_date', models.DateField(blank=True, null=True)),
                ('is_eligible', models.BooleanField(default=True)),
                ('eligibility_reason', models.TextField(blank=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('level', models.CharField(default='Bronze', max_length=50)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('eligibility_status', models.CharField(choices=[('eligible', 'Eligible'), ('temporarily_ineligible', 'Temporarily Ineligible'), ('permanently_ineligible', 'Permanently Ineligible')], default='eligible', max_length=30)),
                ('weight', models.FloatField(blank=True, help_text='Weight in kg', null=True)),
                ('height', models.FloatField(blank=True, help_text='Height in cm', null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_donations'],
                'indexes': [models.Index(fields=['is_eligible'], name='donors_dono_is_elig_5cfa52_idx'), models.Index(fields=['next_eligible_date'], name='donors_dono_next_el_f3202e_idx'), models.Index(fields=['is_available', 'eligibility_status'], name='donors_dono_is_avai_7bac01_idx')],
            },
        ),
    ]
