import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LocalizationService extends StateNotifier<Locale> {
  static const String languageKey = 'language';

  LocalizationService() : super(const Locale('en')) {
    _loadLanguage();
  }

  Future<void> _loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    final language = prefs.getString(languageKey) ?? 'en';
    state = Locale(language);
  }

  Future<void> changeLanguage(String languageCode) async {
    state = Locale(languageCode);
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(languageKey, languageCode);
  }

  String get currentLanguage => state.languageCode;

  String translate(String key) {
    // This is a simple implementation. In production, use proper i18n packages.
    final translations = {
      'en': englishTranslations,
      'fr': frenchTranslations,
    };

    return translations[state.languageCode]?[key] ??
           translations['en']?[key] ??
           key;
  }

  static const Map<String, String> englishTranslations = {
    'welcome': 'Welcome',
    'welcome_back': 'Welcome back',
    'login': 'Login',
    'register': 'Register',
    'forgot_password': 'Forgot Password?',
    'email': 'Email',
    'password': 'Password',
    'confirm_password': 'Confirm Password',
    'full_name': 'Full Name',
    'phone': 'Phone',
    'home': 'Home',
    'donor_dashboard': 'Donor Dashboard',
    'patient_dashboard': 'Patient Dashboard',
    'hospital_dashboard': 'Hospital Dashboard',
    'blood_inventory': 'Blood Inventory',
    'blood_request': 'Request Blood',
    'search_blood': 'Search Blood',
    'emergency_request': 'Emergency Request',
    'donor_list': 'Donor List',
    'chat': 'Chat',
    'notifications': 'Notifications',
    'hospital_locator': 'Hospital Locator',
    'book_appointment': 'Book Appointment',
    'campaigns': 'Campaigns',
    'profile_settings': 'Profile Settings',
    'rewards': 'Rewards',
    'leaderboard': 'Leaderboard',
    'reports': 'Reports',
    'admin_panel': 'Admin Panel',
    'logout': 'Logout',
    'total_donations': 'Total Donations',
    'total_units': 'Total Units',
    'lives_saved': 'Lives Saved',
    'eligibility_status': 'Eligibility',
    'eligible': 'Eligible',
    'ineligible': 'Ineligible',
    'quick_actions': 'Quick Actions',
    'recent_activity': 'Recent Activity',
    'no_donations_yet': 'No donations yet',
    'no_appointments': 'No appointments',
    'no_notifications': 'No notifications',
    'no_requests': 'No requests',
    'no_data_available': 'No data available',
    'submit': 'Submit',
    'cancel': 'Cancel',
    'save': 'Save',
    'delete': 'Delete',
    'edit': 'Edit',
    'view': 'View',
    'search': 'Search',
    'filter': 'Filter',
    'sort': 'Sort',
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'warning': 'Warning',
    'active': 'Active',
    'inactive': 'Inactive',
    'pending': 'Pending',
    'approved': 'Approved',
    'rejected': 'Rejected',
    'completed': 'Completed',
    'cancelled': 'Cancelled',
    'blood_group': 'Blood Group',
    'quantity': 'Quantity',
    'urgency': 'Urgency',
    'hospital': 'Hospital',
    'date': 'Date',
    'time': 'Time',
    'location': 'Location',
    'description': 'Description',
    'notes': 'Notes',
    'reason': 'Reason',
    'status': 'Status',
    'amount': 'Amount',
    'payment': 'Payment',
    'pay_now': 'Pay Now',
    'select_payment_method': 'Select Payment Method',
    'amount_to_pay': 'Amount to Pay',
    'emergency': 'Emergency',
    'send_emergency_request': 'Send Emergency Request',
    'emergency_warning': 'This is an emergency request. All nearby hospitals and donors will be notified immediately.',
    'check_eligibility': 'Check Eligibility',
    'health_questionnaire': 'Health Questionnaire',
    'age': 'Age',
    'weight_kg': 'Weight (kg)',
    'recent_surgeries': 'Recent Surgeries',
    'pregnancy_status': 'Pregnancy Status',
    'infectious_diseases': 'Infectious Diseases',
    'medication_use': 'Medication Use',
    'medical_condition': 'Medical Condition',
    'temporary_ineligible': 'Temporarily Ineligible',
    'permanent_ineligible': 'Permanently Ineligible',
    'donation_history': 'Donation History',
    'appointment_history': 'Appointment History',
    'impact_statistics': 'Impact Statistics',
    'total_points': 'Total Points',
    'current_level': 'Current Level',
    'my_badges': 'My Badges',
    'earned_badges': 'Earned Badges',
    'no_rewards_yet': 'No rewards yet',
    'no_leaderboard_data': 'No leaderboard data',
    'top_donors': 'Top Donors',
    'top_regions': 'Top Regions',
    'community_rank': 'Community Rank',
    'donation_streak': 'Donation Streak',
    'hospital_contributions': 'Hospital Contributions',
    'monthly_impact': 'Monthly Impact',
    'monthly_donations': 'Monthly Donations',
    'blood_stock_by_group': 'Blood Stock by Group',
    'personal_information': 'Personal Information',
    'preferences': 'Preferences',
    'push_notifications': 'Push Notifications',
    'email_notifications': 'Email Notifications',
    'dark_mode': 'Dark Mode',
    'language': 'Language',
    'change_password': 'Change Password',
    'security_settings': 'Security Settings',
    'users': 'Users',
    'hospitals': 'Hospitals',
    'statistics': 'Statistics',
    'total_users': 'Total Users',
    'total_donors': 'Total Donors',
    'total_patients': 'Total Patients',
    'total_hospitals': 'Total Hospitals',
    'active_requests': 'Active Requests',
    'low_stock': 'Low Stock',
    'available': 'Available',
    'hospitals_nearby': 'Hospitals Nearby',
    'no_donors_found': 'No donors found',
    'no_campaigns': 'No campaigns',
    'no_results': 'No results found',
    'book': 'Book',
    'register_now': 'Register Now',
    'back_to_login': 'Back to Login',
    'check_email': 'Check Your Email',
    'reset_email_sent': 'We have sent you a password reset link. Please check your email.',
    'forgot_password_title': 'Forgot Password?',
    'forgot_password_subtitle': 'Enter your email address and we will send you a link to reset your password.',
    'reset_password': 'Reset Password',
    'already_have_account': 'Already have an account?',
    'dont_have_account': "Don't have an account?",
    'create_profile': 'Create Profile',
    'no_donor_profile': 'No donor profile',
    'no_hospital_assigned': 'No hospital assigned',
    'total_blood_units': 'Total Blood Units',
    'low_stock_alerts': 'Low Stock Alerts',
    'pending_appointments': 'Pending Appointments',
    'donor_details': 'Donor Details',
    'contact_information': 'Contact Information',
    'donation_statistics': 'Donation Statistics',
    'call': 'Call',
    'campaign_details': 'Campaign Details',
    'details': 'Details',
    'start_date': 'Start Date',
    'end_date': 'End Date',
    'participants': 'Participants',
    'select_language': 'Select Language',
    'sign_in_to_continue': 'Sign in to continue',
    'enter_email': 'Enter your email',
    'please_enter_email': 'Please enter your email',
    'please_enter_valid_email': 'Please enter a valid email',
    'enter_password': 'Enter your password',
    'please_enter_password': 'Please enter your password',
    'password_length_error': 'Password must be at least 8 characters',
    'create_account': 'Create Account',
    'select_role_subtitle': 'Select your role to get started',
    'role_patient_title': 'Patient',
    'role_patient_desc': 'Request blood and find donors',
    'role_donor_title': 'Donor',
    'role_donor_desc': 'Donate blood and save lives',
    'role_hospital_title': 'Hospital Staff',
    'role_hospital_desc': 'Manage inventory and requests',
    'role_lab_tech_title': 'Lab Technician',
    'role_lab_tech_desc': 'Analyze and validate blood donations',
    'role_admin_title': 'Administrator',
    'role_admin_desc': 'Manage system and users',
    'enter_full_name': 'Enter your full name',
    'please_enter_full_name': 'Please enter your full name',
    'gender': 'Gender',
    'male': 'Male',
    'female': 'Female',
    'please_select_gender': 'Please select gender',
    'date_of_birth': 'Date of Birth',
    'select_dob': 'Select DOB',
    'please_select_blood_group': 'Please select blood group',
    'phone_number': 'Phone Number',
    'enter_phone': 'Enter your phone number',
    'please_enter_phone': 'Please enter your phone number',
    'address': 'Address',
    'enter_address': 'Enter your address',
    'please_enter_address': 'Please enter your address',
    'city': 'City',
    'required': 'Required',
    'region': 'Region',
    'security': 'Security',
    'create_password': 'Create a password',
    'confirm_your_password': 'Confirm your password',
    'passwords_do_not_match': 'Passwords do not match',
    'please_fill_fields': 'Please fill all required fields',
    'tagline': 'Connecting Donors. Saving Lives.',
    'subscription_expired': 'Subscription Expired',
    'subscription_expired_desc': 'Your hospital subscription has expired or been deactivated. Please renew the monthly subscription (25 FCFA/month) to access the application.',
    'renew_subscription': 'Renew Subscription',
    'subscription_active_desc': 'Subscription Active (25 FCFA/mo)',
    'subscription_expired_inactive': 'Subscription Expired / Inactive',
    'valid_until': 'Valid until',
    'expires_today': 'Expires today!',
    'day_remaining': 'day remaining',
    'days_remaining': 'days remaining',
    'hour_remaining': 'hour remaining',
    'hours_remaining': 'hours remaining',
    'invoices': 'Invoices',
    'dashboard': 'Dashboard',
    'receipts': 'Receipts',
    'enable_dark_mode': 'Enable dark mode',
    'registration_success': 'Registration successful!',
    'download_receipt': 'Download Receipt',
    'print_invoice': 'Print Invoice',
    'subscription_history': 'Subscription History',
    'transaction_id': 'Transaction ID',
    'payment_method': 'Payment Method',
    'invoice_number': 'Invoice #',
    'receipt_number': 'Receipt #',
    'period': 'Period',
    'health_records': 'Health Records',
    'digital_badge': 'Digital Donor Badge',
    'emergency_sos': 'EMERGENCY SOS',
    'find_donors': 'Find Donors',
    'available_blood_packs': 'Available Blood Packs',
    'change_password_notice': 'For security reasons, choose a strong password with at least 8 characters.',
    'current_password': 'Current Password',
    'enter_current_password': 'Enter your current password',
    'please_enter_current_password': 'Please enter your current password',
    'new_password': 'New Password',
    'create_new_password': 'Create a new password',
    'confirm_new_password': 'Confirm New Password',
    'password_strength': 'Password Strength',
    'weak': 'Weak',
    'medium': 'Medium',
    'strong': 'Strong',
    'password_requirements_unmet': 'Password does not meet all security requirements.',
    'password_changed_success': 'Password changed successfully.',
    'update_password': 'Update Password',
    'account_security_status': 'Account Security Status',
    'security_status_high': 'High Protection (Recommended configuration)',
    'security_status_medium': 'Medium Protection (Enable 2FA for extra safety)',
    'change_password_desc': 'Update your account login password',
    'authentication_security': 'Authentication & Security',
    'biometric_auth': 'Biometric Authentication',
    'biometric_auth_desc': 'Use fingerprint or face unlock to access the app',
    'two_factor_auth': 'Two-Factor Authentication (2FA)',
    'two_factor_auth_desc': 'Require verification code on sensitive logins',
    'login_notifications': 'Login Security Alerts',
    'login_notifications_desc': 'Receive email notifications when new device logs in',
    'recovery_email': 'Recovery Email',
    'not_configured': 'Not configured',
    'logout_other_devices': 'Log out from all other devices',
    'no_active_sessions': 'No other active sessions found',
    'recent_login_history': 'Recent Login History',
    'no_login_history': 'No login history recorded yet',
    'retry': 'Retry',
    'role': 'Role',
    'role_donor': 'Donor',
    'role_patient': 'Patient',
    'role_hospital_staff': 'Hospital Staff',
    'role_lab_technician': 'Lab Technician',
    'role_admin': 'Administrator',
    'view_all': 'View All',
    'request_blood_now': 'Request Blood Now',
    'find_donors_now': 'Find Donors Now',
    'blood_tests': 'Blood Tests',
    'test_results': 'Test Results',
    'inventory_management': 'Inventory Management',
    'manage_users': 'Manage Users',
    'system_health': 'System Health',
    'analytics': 'Analytics',
    'general_settings': 'General Settings',
    'help_support': 'Help & Support',
    'about_lifelink': 'About LifeLink',
    'logout_confirmation': 'Are you sure you want to log out?',
    'confirm_logout': 'Log Out',
    'yes': 'Yes',
    'no': 'No',
    'close': 'Close',
    'save_changes': 'Save Changes',
    'filter_by_blood_group': 'Filter by Blood Group',
    'select_role': 'Select Role',
    'no_internet_connection': 'No internet connection',
  };

  static const Map<String, String> frenchTranslations = {
    'welcome': 'Bienvenue',
    'welcome_back': 'Bon retour',
    'login': 'Connexion',
    'register': 'Inscription',
    'forgot_password': 'Mot de passe oublié?',
    'email': 'Email',
    'password': 'Mot de passe',
    'confirm_password': 'Confirmer le mot de passe',
    'full_name': 'Nom complet',
    'phone': 'Téléphone',
    'home': 'Accueil',
    'donor_dashboard': 'Tableau de bord des donneurs',
    'patient_dashboard': 'Tableau de bord des patients',
    'hospital_dashboard': 'Tableau de bord des hôpitaux',
    'blood_inventory': 'Inventaire sanguin',
    'blood_request': 'Demande de sang',
    'search_blood': 'Rechercher du sang',
    'emergency_request': 'Demande d\'urgence',
    'donor_list': 'Liste des donneurs',
    'chat': 'Chat',
    'notifications': 'Notifications',
    'hospital_locator': 'Localisateur d\'hôpitaux',
    'book_appointment': 'Prendre rendez-vous',
    'campaigns': 'Campagnes',
    'profile_settings': 'Paramètres du profil',
    'rewards': 'Récompenses',
    'leaderboard': 'Classement',
    'reports': 'Rapports',
    'admin_panel': 'Panneau d\'administration',
    'logout': 'Déconnexion',
    'total_donations': 'Total des dons',
    'total_units': 'Unités totales',
    'lives_saved': 'Vies sauvées',
    'eligibility_status': 'Éligibilité',
    'eligible': 'Éligible',
    'ineligible': 'Non éligible',
    'quick_actions': 'Actions rapides',
    'recent_activity': 'Activité récente',
    'no_donations_yet': 'Pas encore de dons',
    'no_appointments': 'Pas de rendez-vous',
    'no_notifications': 'Pas de notifications',
    'no_requests': 'Pas de demandes',
    'no_data_available': 'Aucune donnée disponible',
    'submit': 'Soumettre',
    'cancel': 'Annuler',
    'save': 'Enregistrer',
    'delete': 'Supprimer',
    'edit': 'Modifier',
    'view': 'Voir',
    'search': 'Rechercher',
    'filter': 'Filtrer',
    'sort': 'Trier',
    'loading': 'Chargement...',
    'error': 'Erreur',
    'success': 'Succès',
    'warning': 'Avertissement',
    'active': 'Actif',
    'inactive': 'Inactif',
    'pending': 'En attente',
    'approved': 'Approuvé',
    'rejected': 'Rejeté',
    'completed': 'Terminé',
    'cancelled': 'Annulé',
    'blood_group': 'Groupe sanguin',
    'quantity': 'Quantité',
    'urgency': 'Urgence',
    'hospital': 'Hôpital',
    'date': 'Date',
    'time': 'Heure',
    'location': 'Emplacement',
    'description': 'Description',
    'notes': 'Notes',
    'reason': 'Raison',
    'status': 'Statut',
    'amount': 'Montant',
    'payment': 'Paiement',
    'pay_now': 'Payer maintenant',
    'select_payment_method': 'Sélectionner le mode de paiement',
    'amount_to_pay': 'Montant à payer',
    'emergency': 'Urgence',
    'send_emergency_request': 'Envoyer la demande d\'urgence',
    'emergency_warning': 'Ceci est une demande d\'urgence. Tous les hôpitaux et donneurs à proximité seront notifiés immédiatement.',
    'check_eligibility': 'Vérifier l\'éligibilité',
    'health_questionnaire': 'Questionnaire de santé',
    'age': 'Âge',
    'weight_kg': 'Poids (kg)',
    'recent_surgeries': 'Chirurgies récentes',
    'pregnancy_status': 'État de grossesse',
    'infectious_diseases': 'Maladies infectieuses',
    'medication_use': 'Utilisation de médicaments',
    'medical_condition': 'Condition médicale',
    'temporary_ineligible': 'Temporairement non éligible',
    'permanent_ineligible': 'Définitivement non éligible',
    'donation_history': 'Historique des dons',
    'appointment_history': 'Historique des rendez-vous',
    'impact_statistics': 'Statistiques d\'impact',
    'total_points': 'Points totaux',
    'current_level': 'Niveau actuel',
    'my_badges': 'Mes badges',
    'earned_badges': 'Badges gagnés',
    'no_rewards_yet': 'Pas encore de récompenses',
    'no_leaderboard_data': 'Aucune donnée de classement',
    'top_donors': 'Meilleurs donneurs',
    'top_regions': 'Meilleures régions',
    'community_rank': 'Rang communautaire',
    'donation_streak': 'Série de dons',
    'hospital_contributions': 'Contributions des hôpitaux',
    'monthly_impact': 'Impact mensuel',
    'monthly_donations': 'Dons mensuels',
    'blood_stock_by_group': 'Stock sanguin par groupe',
    'personal_information': 'Informations personnelles',
    'preferences': 'Préférences',
    'push_notifications': 'Notifications push',
    'email_notifications': 'Notifications par email',
    'dark_mode': 'Mode sombre',
    'language': 'Langue',
    'change_password': 'Changer le mot de passe',
    'security_settings': 'Paramètres de sécurité',
    'users': 'Utilisateurs',
    'hospitals': 'Hôpitaux',
    'statistics': 'Statistiques',
    'total_users': 'Total des utilisateurs',
    'total_donors': 'Total des donneurs',
    'total_patients': 'Total des patients',
    'total_hospitals': 'Total des hôpitaux',
    'active_requests': 'Demandes actives',
    'low_stock': 'Stock faible',
    'available': 'Disponible',
    'hospitals_nearby': 'Hôpitaux à proximité',
    'no_donors_found': 'Aucun donneur trouvé',
    'no_campaigns': 'Aucune campagne',
    'no_results': 'Aucun résultat',
    'book': 'Réserver',
    'register_now': 'S\'inscrire maintenant',
    'back_to_login': 'Retour à la connexion',
    'check_email': 'Vérifiez votre email',
    'reset_email_sent': 'Nous vous avons envoyé un lien de réinitialisation du mot de passe. Veuillez vérifier votre email.',
    'forgot_password_title': 'Mot de passe oublié?',
    'forgot_password_subtitle': 'Entrez votre adresse email et nous vous enverrons un lien pour réinitialiser votre mot de passe.',
    'reset_password': 'Réinitialiser le mot de passe',
    'already_have_account': 'Vous avez déjà un compte?',
    'dont_have_account': 'Vous n\'avez pas de compte?',
    'create_profile': 'Créer un profil',
    'no_donor_profile': 'Aucun profil de donneur',
    'no_hospital_assigned': 'Aucun hôpital assigné',
    'total_blood_units': 'Unités de sang totales',
    'low_stock_alerts': 'Alertes de stock faible',
    'pending_appointments': 'Rendez-vous en attente',
    'donor_details': 'Détails du donneur',
    'contact_information': 'Informations de contact',
    'donation_statistics': 'Statistiques de dons',
    'call': 'Appeler',
    'campaign_details': 'Détails de la campagne',
    'details': 'Détails',
    'start_date': 'Date de début',
    'end_date': 'Date de fin',
    'participants': 'Participants',
    'select_language': 'Choisir la langue',
    'sign_in_to_continue': 'Connectez-vous pour continuer',
    'enter_email': 'Entrez votre adresse email',
    'please_enter_email': 'Veuillez entrer votre adresse email',
    'please_enter_valid_email': 'Veuillez entrer un email valide',
    'enter_password': 'Entrez votre mot de passe',
    'please_enter_password': 'Veuillez entrer votre mot de passe',
    'password_length_error': 'Le mot de passe doit contenir au moins 8 caractères',
    'create_account': 'Créer un compte',
    'select_role_subtitle': 'Sélectionnez votre rôle pour commencer',
    'role_patient_title': 'Patient',
    'role_patient_desc': 'Demander du sang et trouver des donneurs',
    'role_donor_title': 'Donneur',
    'role_donor_desc': 'Donner du sang et sauver des vies',
    'role_hospital_title': 'Personnel hospitalier',
    'role_hospital_desc': "Gérer l'inventaire et les demandes",
    'role_lab_tech_title': 'Technicien de laboratoire',
    'role_lab_tech_desc': 'Analyser et valider les dons de sang',
    'role_admin_title': 'Administrateur',
    'role_admin_desc': 'Gérer le système et les utilisateurs',
    'enter_full_name': 'Entrez votre nom complet',
    'please_enter_full_name': 'Veuillez entrer votre nom complet',
    'gender': 'Genre',
    'male': 'Homme',
    'female': 'Femme',
    'please_select_gender': 'Veuillez sélectionner un genre',
    'date_of_birth': 'Date de naissance',
    'select_dob': 'Sélectionner la date de naissance',
    'please_select_blood_group': 'Veuillez sélectionner un groupe sanguin',
    'phone_number': 'Numéro de téléphone',
    'enter_phone': 'Entrez votre numéro de téléphone',
    'please_enter_phone': 'Veuillez entrer votre numéro de téléphone',
    'address': 'Adresse',
    'enter_address': 'Entrez votre adresse',
    'please_enter_address': 'Veuillez entrer votre adresse',
    'city': 'Ville',
    'required': 'Obligatoire',
    'region': 'Région',
    'security': 'Sécurité',
    'create_password': 'Créer un mot de passe',
    'confirm_your_password': 'Confirmez votre mot de passe',
    'passwords_do_not_match': 'Les mots de passe ne correspondent pas',
    'please_fill_fields': 'Veuillez remplir tous les champs obligatoires',
    'tagline': 'Connecter les donneurs. Sauver des vies.',
    'subscription_expired': 'Abonnement expiré',
    'subscription_expired_desc': 'L\'abonnement de votre hôpital a expiré ou a été désactivé. Veuillez renouveler l\'abonnement mensuel (25 FCFA/mois) pour accéder à l\'application.',
    'renew_subscription': 'Renouveler l\'abonnement',
    'subscription_active_desc': 'Abonnement actif (25 FCFA/mois)',
    'subscription_expired_inactive': 'Abonnement expiré / inactif',
    'valid_until': 'Valide jusqu\'au',
    'expires_today': 'Expire aujourd\'hui !',
    'day_remaining': 'jour restant',
    'days_remaining': 'jours restants',
    'hour_remaining': 'heure restante',
    'hours_remaining': 'heures restantes',
    'invoices': 'Factures',
    'dashboard': 'Tableau de bord',
    'receipts': 'Reçus',
    'enable_dark_mode': 'Activer le mode sombre',
    'registration_success': 'Inscription réussie !',
    'download_receipt': 'Télécharger le reçu',
    'print_invoice': 'Imprimer la facture',
    'subscription_history': 'Historique des abonnements',
    'transaction_id': 'ID de transaction',
    'payment_method': 'Mode de paiement',
    'invoice_number': 'N° de Facture',
    'receipt_number': 'N° de Reçu',
    'period': 'Période',
    'health_records': 'Dossiers médicaux',
    'digital_badge': 'Badge numérique de donneur',
    'emergency_sos': 'SOS URGENCE',
    'find_donors': 'Trouver des donneurs',
    'available_blood_packs': 'Poches de sang disponibles',
    'change_password_notice': 'Pour des raisons de sécurité, choisissez un mot de passe fort d\'au moins 8 caractères.',
    'current_password': 'Mot de passe actuel',
    'enter_current_password': 'Entrez votre mot de passe actuel',
    'please_enter_current_password': 'Veuillez entrer votre mot de passe actuel',
    'new_password': 'Nouveau mot de passe',
    'create_new_password': 'Créer un nouveau mot de passe',
    'confirm_new_password': 'Confirmer le nouveau mot de passe',
    'password_strength': 'Force du mot de passe',
    'weak': 'Faible',
    'medium': 'Moyen',
    'strong': 'Fort',
    'password_requirements_unmet': 'Le mot de passe ne répond pas à toutes les exigences de sécurité.',
    'password_changed_success': 'Mot de passe modifié avec succès.',
    'update_password': 'Mettre à jour le mot de passe',
    'account_security_status': 'Statut de sécurité du compte',
    'security_status_high': 'Haute protection (Configuration recommandée)',
    'security_status_medium': 'Protection moyenne (Activez le 2FA pour plus de sécurité)',
    'change_password_desc': 'Mettre à jour le mot de passe de votre compte',
    'authentication_security': 'Authentification & Sécurité',
    'biometric_auth': 'Authentification biométrique',
    'biometric_auth_desc': 'Utiliser l\'empreinte ou le déverrouillage facial',
    'two_factor_auth': 'Authentification à deux facteurs (2FA)',
    'two_factor_auth_desc': 'Exiger un code de vérification aux connexions sensibles',
    'login_notifications': 'Alertes de sécurité de connexion',
    'login_notifications_desc': 'Recevoir des notifications par email lors des connexions',
    'recovery_email': 'Email de récupération',
    'not_configured': 'Non configuré',
    'logout_other_devices': 'Se déconnecter des autres appareils',
    'no_active_sessions': 'Aucune autre session active trouvée',
    'recent_login_history': 'Historique récent des connexions',
    'no_login_history': 'Aucun historique de connexion enregistré',
    'retry': 'Réessayer',
    'role': 'Rôle',
    'role_donor': 'Donneur',
    'role_patient': 'Patient',
    'role_hospital_staff': 'Personnel hospitalier',
    'role_lab_technician': 'Technicien de laboratoire',
    'role_admin': 'Administrateur',
    'view_all': 'Tout afficher',
    'request_blood_now': 'Demander du sang maintenant',
    'find_donors_now': 'Trouver des donneurs maintenant',
    'blood_tests': 'Analyses de sang',
    'test_results': 'Résultats des tests',
    'inventory_management': 'Gestion de l\'inventaire',
    'manage_users': 'Gérer les utilisateurs',
    'system_health': 'Santé du système',
    'analytics': 'Analytique',
    'general_settings': 'Paramètres généraux',
    'help_support': 'Aide & Support',
    'about_lifelink': 'À propos de LifeLink',
    'logout_confirmation': 'Êtes-vous sûr de vouloir vous déconnecter ?',
    'confirm_logout': 'Déconnexion',
    'yes': 'Oui',
    'no': 'Non',
    'close': 'Fermer',
    'save_changes': 'Enregistrer les modifications',
    'filter_by_blood_group': 'Filtrer par groupe sanguin',
    'select_role': 'Sélectionner un rôle',
    'no_internet_connection': 'Pas de connexion internet',
  };
}

class TranslatedLocalizationService extends LocalizationService {
  final Locale _activeLocale;

  TranslatedLocalizationService(this._activeLocale);

  @override
  Locale get state => _activeLocale;

  @override
  String get currentLanguage => _activeLocale.languageCode;
}
